Library_Management/Library_App/urls.py
from django.conf.urls import url
from Library_App import views

#Template urls

app_name = 'libapp'

urlpatterns=[
url(r'^$',views.index,name='index'),
url(r'^register/$',views.register,name='register'),
url(r'^user_login/$',views.login_page,name='user_login'),
url(r'^profile/$',views.profileoverview,name='profile'),
url(r'^contact/$',views.contactpage,name='contact'),
url(r'^overview/$',views.view_profile,name='special'),
url(r'^books/$',views.view_book,name='viewbook'),
url(r'^search/$',views.search_book,name='search'),

]

Library_Management/Library_Management/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url,include
from Library_App import views
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views

urlpatterns = [
    url(r'^$',views.index,name='index'),
    path('admin/', admin.site.urls),
    url(r'^',include('Library_App.urls')),
    url(r'^overview/$',views.view_profile,name='special'),
    url(r'^user_login/$',views.login_page,name='user_login'),
    url(r'^profile/$',views.profileoverview,name='profile'),
    url(r'^books/$',views.bookoverview,name='books'),
    url(r'^books/$',views.search_book,name='search'),
    path('logout/', auth_views.LogoutView.as_view(next_page=settings.LOGOUT_REDIRECT_URL), name='logout'),

]

if settings.DEBUG: # new
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
    url(r'^__debug__/',include(debug_toolbar.urls))
    ]+urlpatterns

Library_Management/Library_App/models.py
from django.db import models
from django.contrib.auth.models import User
import uuid
from django.utils import timezone
from django.db.models.signals import post_save
# Create your models here.

class UserProfileInfo(models.Model):
#building a one to one releationship with users and
#linking them with the additional attributes created by us
#we dont direclty inherit therefore use the one to one releationship
    user = models.OneToOneField(User,on_delete=models.DO_NOTHING,)


    #additional attributes
    profile_pic = models.ImageField(upload_to='profile_pics',blank=True)

    #return something
    def __str__(self):
        return self.user.username


#def create_profile(sender, **kwargs):
    #if kwargs['created']:
        #user_profile = UserProfileInfo.objects.create(user=kwargs['instance'])

#post_save.connect(create_profile, sender=User)


#class Condition(models.Model):
    #type =  models.CharField(max_length = 30, help_text = "Enter a book Condition(e.g New,Old,Cannot Be used)")
    #def __str__(self):
        #return self.type

class Genre(models.Model):
    gen = models.CharField(max_length = 100, help_text = "Enter a book Genre(e.g Science,Fiction,Non-Fiction)")
    def __str__(self):
        return self.gen

class Language(models.Model):
    lang = models.CharField(max_length = 100, help_text = "Enter a book Language")
    def __str__(self):
        return self.lang

class Purchase_Type(models.Model):
    type = models.CharField(max_length = 100, help_text = "Enter Whether Loan or Purchase")
    def __str__(self):
        return self.type

class Author(models.Model):
    f_name = models.CharField(max_length = 20)
    l_name = models.CharField(max_length = 20)
    def __str__(self):
        return self.f_name

class Publisher(models.Model):
    name = models.CharField(max_length = 20)
    def __str__(self):
        return self.name

class Fine(models.Model):
    fine = models.IntegerField()
    def __str__(self):
        return self.fine


class Book(models.Model):
    author = models.ForeignKey('Author',on_delete=models.CASCADE,max_length = 30)
    publisher = models.ForeignKey('Publisher',on_delete=models.CASCADE,max_length = 30)
    genre  = models.ForeignKey('Genre',help_text = "Enter a book Genre(e.g Science,Fiction,Non-Fiction)",on_delete=models.CASCADE)
    name = models.CharField(max_length = 30)
    edition = models.CharField(max_length = 30)

    def __str__(self):
        return self.name

class Bookinstance(models.Model):

    book = models.ForeignKey('Book',on_delete=models.CASCADE,max_length = 30)
    #condition = models.ForeignKey('Condition',on_delete=models.CASCADE,default='Status Not Available')
    language = models.ForeignKey('Language',on_delete=models.CASCADE,max_length = 30)
    purchase_type =  models.ForeignKey('Purchase_Type',on_delete=models.CASCADE,max_length = 30)
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, help_text = "Unique Id for the book for the entire library")
    status = models.CharField(max_length = 30)
    date_added = models.DateField(default=timezone.now)
    date_modified = models.DateField(default=timezone.now)

    def __str__(self):
        return self.book.name

class Transaction_Detail(models.Model):
    book_instance_id = models.ForeignKey('Bookinstance',on_delete=models.CASCADE,max_length = 30)
    user_id = models.ForeignKey(User,on_delete=models.CASCADE,max_length = 30)
    borrow_id = models.ForeignKey('Borrow_Detail',on_delete=models.CASCADE,max_length = 30)
    fine = models.ForeignKey('Fine',on_delete=models.CASCADE)
    due_date = models.DateField(default=timezone.now)
    return_date = models.DateField(default=timezone.now)
    def __str__(self):
        return self.book_instance_id

class Borrow_Detail(models.Model):
    book_instance_id = models.ForeignKey('Bookinstance',on_delete=models.CASCADE,max_length = 30)
    user_id = models.ForeignKey(User,on_delete=models.CASCADE,max_length = 30)
    fine = models.ForeignKey('Fine',on_delete=models.CASCADE)
    flag_lock = models.IntegerField()
    def __str__(self):
        return self.flag_lock

Library_Management/Library_App/forms.py
from django import forms
from django.contrib.auth.models import User
from Library_App.models import UserProfileInfo

class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())
    confirm_password=forms.CharField(widget=forms.PasswordInput())

    def clean(self):
        cleaned_data = super(UserForm, self).clean()
        password = cleaned_data.get("password")
        confirm_password = cleaned_data.get("confirm_password")

        if password != confirm_password:
            raise forms.ValidationError("The Passwords You Entered Do Not Match")

    class Meta():
        model = User
        fields = ('first_name','last_name','username','email','password')
        help_texts = {
            'username': None,
            'email': None,
        }



class UserProfileInfoForm(forms.ModelForm):
    class Meta():
        model = UserProfileInfo
        fields = ('profile_pic',)

Library_Management/Library_App/views.py
from django.shortcuts import render
from Library_App.forms import UserForm,UserProfileInfoForm

from django.db import connection
#login Logour function
from django.contrib.auth import authenticate,login,logout
from django.http import HttpResponseRedirect, HttpResponse
from django.urls import reverse
from Library_App.models import Book,Bookinstance
from django.contrib.auth.decorators import login_required
from django.views.generic import ListView,DetailView
from Library_App.filter import BookFilter1,BookFilter


def index(request):
    return render(request,'Library_App/Indexpage/index.html')

def login_page(request):
    if request.method == 'POST':
        username = request.POST.get('username') # we use the .get('username') because we used the same in the html file login.html
        password = request.POST.get('password') # we use the .get('password') because we used the same in the html file login.html

        user = authenticate(username=username,password=password)#authentication happend automatically

        if user:
            if user.is_active:
                login(request,user) #just simply login the user if authenticated succesfully
                return HttpResponseRedirect(reverse('special')) #Redirect to home page or profile page
            else:
                return HttpResponse("ACCOUNT NOT ACTIVE")
        else:
            #return render(request,'Library_App/Login_Page/invalid.html')
            print("Someone Tried To Login And Failed")
            print("Username:{} and Password {} ".format(username,password))
            return render(request,'Library_App/Login_Page/invalid.html')
            #return HttpResponse("Invalid login Details Supplied!")
    else:
        return render(request,'Library_App/Login_Page/login.html',{})

def register(request):

    registered = False

    if request.method == "POST":
        user_form = UserForm(data=request.POST) #same variable as we declared in the html file
        profile_form = UserProfileInfoForm(data=request.POST)#same variable as we declared in the html file

        if user_form.is_valid() and profile_form.is_valid():
            user = user_form.save()
            user.set_password(user.password)   #Use to hash the passowrd so that admin cannot see it
            user.save()

            profile = profile_form.save(commit=False)
            profile.user = user

            if 'profile_pic' in request.FILES:
                profile.profile_pic = request.FILES['profile_pic']

            profile.save()

            registered = True

        else:
            print(user_form.errors,profile_form.errors)
    else:
        user_form = UserForm()
        profile_form = UserProfileInfoForm()
    return render(request,'Library_App/Signup_Page/signup.html',
                                {'user_form':user_form,
                                'profile_form':profile_form,
                                'registered':registered})

def view_profile(request, pk=None):
    if pk:
        user = User.objects.get(pk=pk)
    else:
        user = request.user
    args = {'user': user}
    return render(request, 'Library_App/UserPage/index.html', args)


def search_book(request):
    #booklist = Book.objects.all() and Bookinstance.objects.all()
    booklist = Book.objects.all()
    booksearch = BookFilter1(request.GET, queryset=booklist)
    return render(request, 'Library_App/UserPage/search.html',{'booksearch':booksearch})

def view_book(request):
    book= None

    with connection.cursor() as cursor:
        cursor.execute('SELECT b.name, a.f_name ,a.l_name, g.gen, b.edition,l.lang, bi.status FROM Library_App_book b JOIN Library_App_bookinstance bi ON (b.id=bi.book_id) JOIN Library_App_author a ON (a.id=b.author_id) JOIN Library_App_genre g ON (g.id=b.genre_id) JOIN Library_App_language l ON (l.id=bi.language_id);')
        book = cursor.fetchall()
    context = {
    'book' : book,
    }
    return render(request, 'Library_App/UserPage/book.html',context)


def profileoverview(request):
    return render(request,'Library_App/UserPage/profile.html')

def bookoverview(request):
    return render(request,'Library_App/UserPage/book.html')

def contactpage(request):
    return render(request,'Library_App/UserPage/contact.html')

Library_Management/templates/Library_App/Login_Page/invalid.html
<!DOCTYPE html>
{% load staticfiles %}
<html lang="en">
<head>

	<title>Login</title>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

	<meta name="description" content="" />
	<meta name="keywords" content="" />
	<meta name="author" content="" />



	<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Poppins:200,300,400,700,900|Display+Playfair:200,300,400,700">
	<link rel="stylesheet" href="{% static "Loginpage/fonts/icomoon/style.css" %}"/>

	<link rel="stylesheet" href="{% static "Loginpage/css/bootstrap.min.css" %}"/>
	<link rel="stylesheet" href="{% static "Loginpage/css/magnific-popup.css" %}"/>
	<link rel="stylesheet" href="{% static "Loginpage/css/jquery-ui.css" %}"/>
	<link rel="stylesheet" href="{% static "Loginpage/css/owl.carousel.min.css" %}"/>
	<link rel="stylesheet" href="{% static "Loginpage/css/owl.theme.default.min.css" %}"/>

	<link rel="stylesheet" href="{% static "Loginpage/css/bootstrap-datepicker.css" %}"/>

	<link rel="stylesheet" href="{% static "Loginpage/fonts/flaticon/font/flaticon.css" %}"/>



	<link rel="stylesheet" href="{% static "Loginpage/css/aos.css" %}"/>

	<link rel="stylesheet" href="{% static "Loginpage/css/style.css" %}"/>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
<!--===============================================================================================-->
	<link rel="icon" type="image/png" href="{% static "Loginpage/images/icons/favicon.ico" %}"/>
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static "Loginpage/vendor/bootstrap/css/bootstrap.min.css" %}"/>
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static "Loginpage/fonts/font-awesome-4.7.0/css/font-awesome.min.css" %}"/>
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static "Loginpage/fonts/Linearicons-Free-v1.0.0/icon-font.min.css" %}"/>
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static "Loginpage/vendor/animate/animate.css" %}"/>
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static "Loginpage/vendor/css-hamburgers/hamburgers.min.css" %}"/>
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static "Loginpage/vendor/select2/select2.min.css" %}"/>
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static "Loginpage/css/util.css" %}"/>
	<link rel="stylesheet" type="text/css" href="{% static "Loginpage/css/main.css" %}"/>
<!--===============================================================================================-->
</head>
<body>

	<div class="limiter">
		<div class="container-login100" style="background-image: url({% static "Loginpage/images/lib02.jpg" %});">
			<div class="wrap-login100 p-t-190 p-b-30">

				<form class="login100-form validate-form" method="post">
					{% csrf_token %}
					<div class="login100-form-avatar">
						<img src="{% static "Loginpage/images/avatar.jpg" %}" "alt="AVATAR"">
					</div>

					<span class="login100-form-title p-t-20 p-b-45">
						LOGIN
					</span>
          <span class="login100-form-title p-t-20 p-b-45">
            Invalid Credenditals!!
          </span>

					<div class="wrap-input100 validate-input m-b-10" data-validate = "Username is required">
						<input class="input100" type="text" name="username" placeholder="Username">
						<span class="focus-input100"></span>
						<span class="symbol-input100">
							<i class="fa fa-user"></i>
						</span>
					</div>

					<div class="wrap-input100 validate-input m-b-10" data-validate = "Password is required">
						<input class="input100" type="password" name="password" placeholder="Password">
						<span class="focus-input100"></span>
						<span class="symbol-input100">
							<i class="fa fa-lock"></i>
						</span>
					</div>

					<div class="container-login100-form-btn p-t-10">
						<button class="login100-form-btn">
							Login
						</button>
					</div>

					<div class="text-center w-full p-t-25 p-b-230">
						<a href="#" class="txt1">
							Forgot Username / Password?
						</a>
					</div>


				</form>
			</div>
		</div>
	</div>





	<script src="{% static "Loginpage/vendor/jquery/jquery-3.2.1.min.js" %}"></script>

	<script src="{% static "Loginpage/vendor/bootstrap/js/popper.js" %}"></script>

	<script src="{% static "Loginpage/vendor/bootstrap/js/bootstrap.min.js" %}"></script>

	<script src="{% static "Loginpage/vendor/select2/select2.min.js" %}"></script>

	<script src="{% static "Loginpage/js/main.js" %}"></script>

</body>
</html>

Library_Management/templates/Library_App/Login_Page/login.html
<!DOCTYPE html>
{% load staticfiles %}
<html lang="en">
<head>

	<title>Login</title>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

	<meta name="description" content="" />
	<meta name="keywords" content="" />
	<meta name="author" content="" />



	<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Poppins:200,300,400,700,900|Display+Playfair:200,300,400,700">
	<link rel="stylesheet" href="{% static "Loginpage/fonts/icomoon/style.css" %}"/>

	<link rel="stylesheet" href="{% static "Loginpage/css/bootstrap.min.css" %}"/>
	<link rel="stylesheet" href="{% static "Loginpage/css/magnific-popup.css" %}"/>
	<link rel="stylesheet" href="{% static "Loginpage/css/jquery-ui.css" %}"/>
	<link rel="stylesheet" href="{% static "Loginpage/css/owl.carousel.min.css" %}"/>
	<link rel="stylesheet" href="{% static "Loginpage/css/owl.theme.default.min.css" %}"/>

	<link rel="stylesheet" href="{% static "Loginpage/css/bootstrap-datepicker.css" %}"/>

	<link rel="stylesheet" href="{% static "Loginpage/fonts/flaticon/font/flaticon.css" %}"/>



	<link rel="stylesheet" href="{% static "Loginpage/css/aos.css" %}"/>

	<link rel="stylesheet" href="{% static "Loginpage/css/style.css" %}"/>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
<!--===============================================================================================-->
	<link rel="icon" type="image/png" href="{% static "Loginpage/images/icons/favicon.ico" %}"/>
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static "Loginpage/vendor/bootstrap/css/bootstrap.min.css" %}"/>
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static "Loginpage/fonts/font-awesome-4.7.0/css/font-awesome.min.css" %}"/>
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static "Loginpage/fonts/Linearicons-Free-v1.0.0/icon-font.min.css" %}"/>
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static "Loginpage/vendor/animate/animate.css" %}"/>
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static "Loginpage/vendor/css-hamburgers/hamburgers.min.css" %}"/>
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static "Loginpage/vendor/select2/select2.min.css" %}"/>
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static "Loginpage/css/util.css" %}"/>
	<link rel="stylesheet" type="text/css" href="{% static "Loginpage/css/main.css" %}"/>
<!--===============================================================================================-->
</head>
<body>

	<div class="limiter">
		<div class="container-login100" style="background-image: url({% static "Loginpage/images/lib02.jpg" %});">
			<div class="wrap-login100 p-t-190 p-b-30">
				
				<form action="{% url 'libapp:user_login' %}" class="login100-form validate-form" method="post">
					{% csrf_token %}
					<div class="login100-form-avatar">
						<img src="{% static "Loginpage/images/avatar.jpg" %}" "alt="AVATAR"">
					</div>

					<span class="login100-form-title p-t-20 p-b-45">
						LOGIN
					</span>

					<div class="wrap-input100 validate-input m-b-10" data-validate = "Username is required">
						<input class="input100" type="text" name="username" placeholder="Username">
						<span class="focus-input100"></span>
						<span class="symbol-input100">
							<i class="fa fa-user"></i>
						</span>
					</div>

					<div class="wrap-input100 validate-input m-b-10" data-validate = "Password is required">
						<input class="input100" type="password" name="password" placeholder="Password">
						<span class="focus-input100"></span>
						<span class="symbol-input100">
							<i class="fa fa-lock"></i>
						</span>
					</div>

					<div class="container-login100-form-btn p-t-10">
						<button class="login100-form-btn">
							Login
						</button>
					</div>

					<div class="text-center w-full p-t-25 p-b-230">
						<a href="#" class="txt1">
							Forgot Username / Password?
						</a>
					</div>

					<div class="text-center w-full">
						<a class="txt1" href="#">
							Create new account
							<i class="fa fa-long-arrow-right"></i>
						</a>
					</div>
				</form>
			</div>
		</div>
	</div>





	<script src="{% static "Loginpage/vendor/jquery/jquery-3.2.1.min.js" %}"></script>

	<script src="{% static "Loginpage/vendor/bootstrap/js/popper.js"%}"> </script>
	<script src="{% static "Loginpage/vendor/bootstrap/js/bootstrap.min.js" %}"></script>

	<script src="{% static "Loginpage/vendor/select2/select2.min.js" %}"></script>

	<script src="{% static "Loginpage/js/main.js" %}"></script>

</body>
</html>