Library_Management/Library_App/urls.py
from django.conf.urls import url
from Library_App import views

#Template urls

app_name = 'libapp'

urlpatterns=[
url(r'^$',views.index,name='index'),
url(r'^register/$',views.register,name='register'),
url(r'^user_login/$',views.login_page,name='user_login'),
url(r'^profile/$',views.profileoverview,name='profile'),
url(r'^contact/$',views.contactpage,name='contact'),
url(r'^overview/$',views.view_profile,name='special'),
url(r'^books/$',views.view_book,name='viewbook'),
url(r'^search/$',views.search_book,name='search'),

]

Library_Management/Library_Management/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url,include
from Library_App import views
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views

urlpatterns = [
    url(r'^$',views.index,name='index'),
    path('admin/', admin.site.urls),
    url(r'^',include('Library_App.urls')),
    url(r'^overview/$',views.view_profile,name='special'),
    url(r'^user_login/$',views.login_page,name='user_login'),
    url(r'^profile/$',views.profileoverview,name='profile'),
    url(r'^books/$',views.bookoverview,name='books'),
    url(r'^books/$',views.search_book,name='search'),
    path('logout/', auth_views.LogoutView.as_view(next_page=settings.LOGOUT_REDIRECT_URL), name='logout'),

]

if settings.DEBUG: # new
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
    url(r'^__debug__/',include(debug_toolbar.urls))
    ]+urlpatterns

Library_Management/Library_App/models.py
from django.db import models
from django.contrib.auth.models import User
import uuid
from django.utils import timezone
from django.db.models.signals import post_save
# Create your models here.

class UserProfileInfo(models.Model):
#building a one to one releationship with users and
#linking them with the additional attributes created by us
#we dont direclty inherit therefore use the one to one releationship
    user = models.OneToOneField(User,on_delete=models.DO_NOTHING,)


    #additional attributes
    profile_pic = models.ImageField(upload_to='profile_pics',blank=True)

    #return something
    def __str__(self):
        return self.user.username


#def create_profile(sender, **kwargs):
    #if kwargs['created']:
        #user_profile = UserProfileInfo.objects.create(user=kwargs['instance'])

#post_save.connect(create_profile, sender=User)


#class Condition(models.Model):
    #type =  models.CharField(max_length = 30, help_text = "Enter a book Condition(e.g New,Old,Cannot Be used)")
    #def __str__(self):
        #return self.type

class Genre(models.Model):
    gen = models.CharField(max_length = 100, help_text = "Enter a book Genre(e.g Science,Fiction,Non-Fiction)")
    def __str__(self):
        return self.gen

class Language(models.Model):
    lang = models.CharField(max_length = 100, help_text = "Enter a book Language")
    def __str__(self):
        return self.lang

class Purchase_Type(models.Model):
    type = models.CharField(max_length = 100, help_text = "Enter Whether Loan or Purchase")
    def __str__(self):
        return self.type

class Author(models.Model):
    f_name = models.CharField(max_length = 20)
    l_name = models.CharField(max_length = 20)
    def __str__(self):
        return self.f_name

class Publisher(models.Model):
    name = models.CharField(max_length = 20)
    def __str__(self):
        return self.name

class Fine(models.Model):
    fine = models.IntegerField()
    def __str__(self):
        return self.fine


class Book(models.Model):
    author = models.ForeignKey('Author',on_delete=models.CASCADE,max_length = 30)
    publisher = models.ForeignKey('Publisher',on_delete=models.CASCADE,max_length = 30)
    genre  = models.ForeignKey('Genre',help_text = "Enter a book Genre(e.g Science,Fiction,Non-Fiction)",on_delete=models.CASCADE)
    name = models.CharField(max_length = 30)
    edition = models.CharField(max_length = 30)

    def __str__(self):
        return self.name

class Bookinstance(models.Model):

    book = models.ForeignKey('Book',on_delete=models.CASCADE,max_length = 30)
    #condition = models.ForeignKey('Condition',on_delete=models.CASCADE,default='Status Not Available')
    language = models.ForeignKey('Language',on_delete=models.CASCADE,max_length = 30)
    purchase_type =  models.ForeignKey('Purchase_Type',on_delete=models.CASCADE,max_length = 30)
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, help_text = "Unique Id for the book for the entire library")
    status = models.CharField(max_length = 30)
    date_added = models.DateField(default=timezone.now)
    date_modified = models.DateField(default=timezone.now)

    def __str__(self):
        return self.book.name

class Transaction_Detail(models.Model):
    book_instance_id = models.ForeignKey('Bookinstance',on_delete=models.CASCADE,max_length = 30)
    user_id = models.ForeignKey(User,on_delete=models.CASCADE,max_length = 30)
    borrow_id = models.ForeignKey('Borrow_Detail',on_delete=models.CASCADE,max_length = 30)
    fine = models.ForeignKey('Fine',on_delete=models.CASCADE)
    due_date = models.DateField(default=timezone.now)
    return_date = models.DateField(default=timezone.now)
    def __str__(self):
        return self.book_instance_id

class Borrow_Detail(models.Model):
    book_instance_id = models.ForeignKey('Bookinstance',on_delete=models.CASCADE,max_length = 30)
    user_id = models.ForeignKey(User,on_delete=models.CASCADE,max_length = 30)
    fine = models.ForeignKey('Fine',on_delete=models.CASCADE)
    flag_lock = models.IntegerField()
    def __str__(self):
        return self.flag_lock

Library_Management/Library_App/forms.py
from django import forms
from django.contrib.auth.models import User
from Library_App.models import UserProfileInfo

class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())
    confirm_password=forms.CharField(widget=forms.PasswordInput())

    def clean(self):
        cleaned_data = super(UserForm, self).clean()
        password = cleaned_data.get("password")
        confirm_password = cleaned_data.get("confirm_password")

        if password != confirm_password:
            raise forms.ValidationError("The Passwords You Entered Do Not Match")

    class Meta():
        model = User
        fields = ('first_name','last_name','username','email','password')
        help_texts = {
            'username': None,
            'email': None,
        }



class UserProfileInfoForm(forms.ModelForm):
    class Meta():
        model = UserProfileInfo
        fields = ('profile_pic',)

Library_Management/Library_App/views.py
from django.shortcuts import render
from Library_App.forms import UserForm,UserProfileInfoForm

from django.db import connection
#login Logour function
from django.contrib.auth import authenticate,login,logout
from django.http import HttpResponseRedirect, HttpResponse
from django.urls import reverse
from Library_App.models import Book,Bookinstance
from django.contrib.auth.decorators import login_required
from django.views.generic import ListView,DetailView
from Library_App.filter import BookFilter1,BookFilter


def index(request):
    return render(request,'Library_App/Indexpage/index.html')

def login_page(request):
    if request.method == 'POST':
        username = request.POST.get('username') # we use the .get('username') because we used the same in the html file login.html
        password = request.POST.get('password') # we use the .get('password') because we used the same in the html file login.html

        user = authenticate(username=username,password=password)#authentication happend automatically

        if user:
            if user.is_active:
                login(request,user) #just simply login the user if authenticated succesfully
                return HttpResponseRedirect(reverse('special')) #Redirect to home page or profile page
            else:
                return HttpResponse("ACCOUNT NOT ACTIVE")
        else:
            #return render(request,'Library_App/Login_Page/invalid.html')
            print("Someone Tried To Login And Failed")
            print("Username:{} and Password {} ".format(username,password))
            return render(request,'Library_App/Login_Page/invalid.html')
            #return HttpResponse("Invalid login Details Supplied!")
    else:
        return render(request,'Library_App/Login_Page/login.html',{})

def register(request):

    registered = False

    if request.method == "POST":
        user_form = UserForm(data=request.POST) #same variable as we declared in the html file
        profile_form = UserProfileInfoForm(data=request.POST)#same variable as we declared in the html file

        if user_form.is_valid() and profile_form.is_valid():
            user = user_form.save()
            user.set_password(user.password)   #Use to hash the passowrd so that admin cannot see it
            user.save()

            profile = profile_form.save(commit=False)
            profile.user = user

            if 'profile_pic' in request.FILES:
                profile.profile_pic = request.FILES['profile_pic']

            profile.save()

            registered = True

        else:
            print(user_form.errors,profile_form.errors)
    else:
        user_form = UserForm()
        profile_form = UserProfileInfoForm()
    return render(request,'Library_App/Signup_Page/signup.html',
                                {'user_form':user_form,
                                'profile_form':profile_form,
                                'registered':registered})

def view_profile(request, pk=None):
    if pk:
        user = User.objects.get(pk=pk)
    else:
        user = request.user
    args = {'user': user}
    return render(request, 'Library_App/UserPage/index.html', args)


def search_book(request):
    #booklist = Book.objects.all() and Bookinstance.objects.all()
    booklist = Book.objects.all()
    booksearch = BookFilter1(request.GET, queryset=booklist)
    return render(request, 'Library_App/UserPage/search.html',{'booksearch':booksearch})

def view_book(request):
    book= None

    with connection.cursor() as cursor:
        cursor.execute('SELECT b.name, a.f_name ,a.l_name, g.gen, b.edition,l.lang, bi.status FROM Library_App_book b JOIN Library_App_bookinstance bi ON (b.id=bi.book_id) JOIN Library_App_author a ON (a.id=b.author_id) JOIN Library_App_genre g ON (g.id=b.genre_id) JOIN Library_App_language l ON (l.id=bi.language_id);')
        book = cursor.fetchall()
    context = {
    'book' : book,
    }
    return render(request, 'Library_App/UserPage/book.html',context)


def profileoverview(request):
    return render(request,'Library_App/UserPage/profile.html')

def bookoverview(request):
    return render(request,'Library_App/UserPage/book.html')

def contactpage(request):
    return render(request,'Library_App/UserPage/contact.html')

Library_Management/templates/Library_App/UserPage/book.html
<!DOCTYPE html>
{% load staticfiles %}
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta name="description" content="Creative - Bootstrap 3 Responsive Admin Template">
  <meta name="author" content="GeeksLabs">
  <meta name="keyword" content="Creative, Dashboard, Admin, Template, Theme, Bootstrap, Responsive, Retina, Minimal">
  <link rel="shortcut icon" href="img/favicon.png">

  <title>Book Page</title>

  <!-- Bootstrap CSS -->
  <link href="{% static "UserPage/css/bootstrap.min.css" %}" rel="stylesheet">
  <!-- bootstrap theme -->
  <link href="{% static "UserPage/css/bootstrap-theme.css" %}" rel="stylesheet">
  <!--external css-->
  <!-- font icon -->
  <link href="{% static "UserPage/css/elegant-icons-style.css" %}" rel="stylesheet" />
  <link href="{% static "UserPage/css/font-awesome.min.css" %}" rel="stylesheet" />
  <!-- Custom styles -->
  <link href="{% static "UserPage/css/style.css" %}" rel="stylesheet">
  <link href="{% static "UserPage/css/style-responsive.css" %}" rel="stylesheet" />

  <style>
b.font_heading{
  font : 20px arial, sans-serif ;
  color : darkblue;
}
  </style>
</head>

<body>
  <!-- container section start -->
  <section id="container" class="">
    <!--header start-->

    <header class="header dark-bg">
      <div class="toggle-nav">
        <div class="icon-reorder tooltips" data-original-title="Toggle Navigation" data-placement="bottom"><i class="icon_menu"></i></div>
      </div>

      <!--logo start-->
      <a  class="logo"> <span class="lite">Books</span></a>
      <!--logo end-->



      <div class="top-nav notification-row">
        <!-- notificatoin dropdown start-->
        <ul class="nav pull-right top-menu">

          <!-- task notificatoin start -->

          <!-- inbox notificatoin end -->
          <!-- alert notification start-->


          <!-- alert notification end-->
          <!-- user login dropdown start-->
          <li class="dropdown">
            <a data-toggle="dropdown" class="dropdown-toggle" href="#">
                            <span class="profile-ava">
                                <img alt="" src="{{ user.userprofileinfo.profile_pic.url }}" width ="40">
                            </span>
                            <span class="username">  {{ user.first_name}}  {{ user.last_name}}</span>
                            <b class="caret"></b>
                        </a>
            <ul class="dropdown-menu extended logout">
              <div class="log-arrow-up"></div>
              <li class="eborder-top">
                <a href="{%url 'libapp:profile'%}"><i class="icon_profile"></i> MY PROFILE</a>
              </li>

              <li>
                <a href="{% url 'logout' %}"><i class="icon_key_alt"></i> Log Out</a>
              </li>

            </ul>
          </li>
          <!-- user login dropdown end -->
        </ul>
        <!-- notificatoin dropdown end-->
      </div>
    </header>
    <!--header end-->

    <!--sidebar start-->
    <aside>
      <div id="sidebar" class="nav-collapse ">
        <!-- sidebar menu start-->
        <ul class="sidebar-menu">
          <li class="">
            <a class="" href="{%url 'libapp:special'%}">
                          <i class="icon_house_alt"></i>
                          <span>Dashboard</span>
                      </a>
          </li>

          <li class="sub-menu ">
            <a href="javascript:;" class="">
                          <i class="icon_documents_alt"></i>
                          <span>Pages</span>
                          <span class="menu-arrow arrow_carrot-right"></span>
                      </a>
            <ul class="sub">
              <li><a class="" href="{%url 'libapp:profile'%}">Profile</a></li>
              <li><a class="" href="{%url 'libapp:contact'%}"><span>Contact Page</span></a></li>
              <li><a class="" href="{%url 'libapp:search'%}">Search Books</a></li>
            </ul>
          </li>

        </ul>
        <!-- sidebar menu end-->
      </div>
    </aside>
    <!--sidebar end-->

    <!--main content start-->
    <section id="main-content">
      <section class="wrapper">
        <div class="row">
          <div class="col-lg-12">
            <h3 class="page-header"><i class="fa fa fa-bars"></i> Book</h3>
            <ol class="breadcrumb">
              <li><i class="fa fa-home"></i><a href="{%url 'libapp:special'%}">Home</a></li>
              <li><i class="fa fa-bars"></i>Pages</li>
              <li><i class="fa fa-book"></i>Book</li>
            </ol>
          </div>
        </div>
        <!-- page start-->
        <div class="col-lg-8">
          <!--Project Activity start-->
          <section class="panel">
            <div class="panel-body progress-panel">
              <div class="row">
                <div class="col-lg-8 task-progress pull-left">
                  <h1>Book Record</h1>
                </div>

              </div>
            </div>
            <form action="" method="GET">
              <input type="text" name="q"  placeholder="SeachPost">
              <input type="Submit" name="" value="Search">
            </form>
            <table class="table table-hover personal-task">
              <tbody>
                <tr>
                  <td><b class="font_heading">Book Name</b></td>
                  <td><b class="font_heading">Author</b></td>
                  <td><b class="font_heading">Genre</b></td>
                  <td><b class="font_heading">Edition</b></td>
                  <td><b class="font_heading">Language</b></td>
                  <td><b class="font_heading">Availability</b></td>
                </tr>

                {% for detail in book %}
                <tr>
                  <td>{{detail.0}}</td>
                  <td>{{detail.1}} {{detail.2}}</td>
                  <td>{{detail.3}}</td>
                  <td>{{detail.4}}</td>
                  <td>{{detail.5}}</td>
                  <td>{{detail.6}}</td>
                </tr>
                {% endfor %}
              </tbody>
            </table>
          </section>
          <!--Project Activity end-->
        </div>
      </div><br><br>
  </section>
        <!-- page end-->
      </section>
    </section>
    <!--main content end-->

  </section>
  <!-- container section end -->
  <!-- javascripts -->
  <script src="{% static "UserPage/js/jquery.js" %}"></script>
  <script src="{% static "UserPage/js/bootstrap.min.js" %}"></script>
  <!-- nice scroll -->
  <script src="{% static "UserPage/js/jquery.scrollTo.min.js" %}"></script>
  <script type="text/javascript" src="{% static "UserPage/js/jquery.nicescroll.js" %}" ></script>
  <!--custome script for all page-->
  <script src="{% static "UserPage/js/scripts.js" %}"></script>


</body>

</html>

Library_Management/templates/Library_App/UserPage/index.html
<!DOCTYPE html>
{% load staticfiles %}

<html lang="en">

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta name="description" content="Creative - Bootstrap 3 Responsive Admin Template">
  <meta name="author" content="GeeksLabs">
  <meta name="keyword" content="Creative, Dashboard, Admin, Template, Theme, Bootstrap, Responsive, Retina, Minimal">
  <link rel="shortcut icon" href="{% static "UserPage/img/favicon.png" %}">



  <!-- Bootstrap CSS -->
  <link rel="stylesheet" href="{% static "UserPage/css/bootstrap.min.css" %}" />
  <!-- bootstrap theme -->
  <link rel="stylesheet" href="{% static "UserPage/css/bootstrap-theme.css" %}"/>
  <!--external css-->
  <!-- font icon -->
  <link rel="stylesheet" href="{% static "UserPage/css/elegant-icons-style.css" %}" />
  <link rel="stylesheet" href="{% static "UserPage/css/font-awesome.min.css" %}" />
  <!-- full calendar css-->
  <link rel="stylesheet" href="{% static "UserPage/assets/fullcalendar/fullcalendar/bootstrap-fullcalendar.css" %}"/>
  <link rel="stylesheet" href="{% static "UserPage/assets/fullcalendar/fullcalendar/fullcalendar.css" %}"/>
  <!-- easy pie chart-->
  <link rel="stylesheet" href="{% static "UserPage/assets/jquery-easy-pie-chart/jquery.easy-pie-chart.css" %}" type="text/css" media="screen" />
  <!-- owl carousel -->
  <link rel="stylesheet" type="text/css" href="{% static "UserPage/css/owl.carousel.css" %}">
  <link rel="stylesheet" href="{% static "UserPage/css/jquery-jvectormap-1.2.2.css" %}">
  <!-- Custom styles -->
  <link rel="stylesheet" href="{% static "UserPage/css/fullcalendar.css" %}"/>
  <link rel="stylesheet" href="{% static "UserPage/css/widgets.css"  %}"/>
  <link rel="stylesheet" href="{% static "UserPage/css/style.css"  %}"/>
  <link rel="stylesheet" href="{% static "UserPage/css/style-responsive.css" %}" />
  <link rel="stylesheet" href="{% static "UserPage/css/xcharts.min.css" %}" />
  <link rel="stylesheet" href="{% static "UserPage/css/jquery-ui-1.10.4.min.css" %}" />
  <title>Dashboard</title>

  </head>

  <body>
  <!-- container section start -->
  <section id="container" class="">


    <header class="header dark-bg">
      <div class="toggle-nav">
        <div class="icon-reorder tooltips" data-original-title="Toggle Navigation" data-placement="bottom"><i class="icon_menu"></i></div>
      </div>

      <!--logo start-->
      <a class="logo">Welcome - <span class="lite"> {{  user.first_name}} {{ user.last_name}}</span></a>
      <!--logo end-->



      <div class="top-nav notification-row">
        <!-- notificatoin dropdown start-->
        <ul class="nav pull-right top-menu">

          <!-- task notificatoin start -->
          <!-- task notificatoin end -->
          <!-- inbox notificatoin start-->
          <li id="mail_notificatoin_bar" class="dropdown">
            <a data-toggle="dropdown" class="dropdown-toggle">

                            <span class="badge bg-important"></span>
                        </a>

          <!-- alert notification end-->
          <!-- user login dropdown start-->
          <li class="dropdown">
            <a data-toggle="dropdown" class="dropdown-toggle" href="#">
                            <span class="profile-ava">
                                <img src="{{ user.userprofileinfo.profile_pic.url }}" width ="40">
                            </span>
                            <span class="username">{{ user.username}}</span>
                            <b class="caret"></b>
                        </a>
            <ul class="dropdown-menu extended logout">
              <div class="log-arrow-up"></div>
              <li class="eborder-top">
                <a href="{%url 'libapp:profile'%}"><i class="icon_profile"></i> My Profile</a>
              </li>
              <li>
                <a href="{% url 'logout' %}"><i class="icon_key_alt"></i> Log Out</a>
              </li>

            </ul>
          </li>
          <!-- user login dropdown end -->
        </ul>
        <!-- notificatoin dropdown end-->
      </div>
    </header>
    <!--header end-->

    <!--sidebar start-->
    <aside>
      <div id="sidebar" class="nav-collapse ">
        <!-- sidebar menu start-->
        <ul class="sidebar-menu">
          <li class="active">
            <a class="" href="{%url 'libapp:special'%}">
                          <i class="icon_house_alt"></i>
                          <span>Dashboard</span>
                      </a>
          </li>
         <li class="sub-menu">
            <a href="javascript:;" class="">
                          <i class="icon_documents_alt"></i>
                          <span>Pages</span>
                          <span class="menu-arrow arrow_carrot-right"></span>
                      </a>
            <ul class="sub">
              <li><a class="" href="{%url 'libapp:profile'%}">Profile</a></li>
              <li><a class="" href="{%url 'libapp:contact'%}"><span>Contact Page</span></a></li>
              <li><a class="" href="{%url 'libapp:viewbook'%}">Books</a></li>
              <li><a class="" href="{%url 'libapp:search'%}">Search Books</a></li>

            </ul>
          </li>

        </ul>
        <!-- sidebar menu end-->
      </div>
    </aside>
    <!--sidebar end-->

    <!--main content start-->
    <section id="main-content">
      <section class="wrapper">
        <!--overview start-->
        <div class="row">
          <div class="col-lg-12">
            <h3 class="page-header"><i class="fa fa-laptop"></i> Dashboard</h3>
            <ol class="breadcrumb">
              <li><i class="fa fa-home"></i><a href="index.html">Home</a></li>
              <li><i class="fa fa-laptop"></i>Dashboard</li>
            </ol>
          </div>
        </div>

        </div>
        <!--/.row-->


        <!-- project team & activity start -->

                <!-- Widget footer -->


          <div class="col-lg-8">
            <!--Project Activity start-->
            <section class="panel">
              <div class="panel-body progress-panel">
                <div class="row">
                  <div class="col-lg-8 task-progress pull-left">
                    <h1>Book Record</h1>
                  </div>

                </div>
              </div>
              <table class="table table-hover personal-task">
                <tbody>
                  <tr>
                    <td>Book Name</td>
                    <td>Issue Date</td>
                    <td>Due Date</td>
                    <td>Fine</td>
                  </tr>
                </tbody>
              </table>
            </section>
            <!--Project Activity end-->
          </div>
        </div><br><br>
    </section>


  <!-- javascripts -->
  <script src="{% static "UserPage/js/jquery.js" %}"></script>
  <script src="{% static "UserPage/js/jquery-ui-1.10.4.min.js" %}"></script>
  <script src="{% static "UserPage/js/jquery-1.8.3.min.js" %}"></script>
  <script type="text/javascript" src="{% static "js/jquery-ui-1.9.2.custom.min.js" %}"></script>
  <!-- bootstrap -->
  <script src="{% static "UserPage/js/bootstrap.min.js" %}"></script>
  <!-- nice scroll -->
  <script src="{% static "UserPage/js/jquery.scrollTo.min.js" %}"></script>
  <script src="{% static "UserPage/js/jquery.nicescroll.js" %}" type="text/javascript"></script>
  <!-- charts scripts -->
  <script src="{% static "UserPage/assets/jquery-knob/js/jquery.knob.js" %}"></script>
  <script src="{% static "UserPage/js/jquery.sparkline.js" %}" type="text/javascript"></script>
  <script src="{% static "UserPage/assets/jquery-easy-pie-chart/jquery.easy-pie-chart.js" %}"></script>
  <script src="{% static "UserPage/js/owl.carousel.js" %}"></script>
  <!-- jQuery full calendar -->
  <script src="{% static "UserPage/js/fullcalendar.min.js" %}"></script>
    <!-- Full Google Calendar - Calendar -->
    <script src="{% static "UserPage/assets/fullcalendar/fullcalendar/fullcalendar.js" %}"></script>
    <!--script for this page only-->
    <script src="{% static "UserPage/js/calendar-custom.js" %}"></script>
    <script src="{% static "UserPage/js/jquery.rateit.min.js" %}"></script>
    <!-- custom select -->
    <script src="{% static "UserPage/js/jquery.customSelect.min.js" %}"></script>
    <script src="{% static "UserPage/assets/chart-master/Chart.js" %}"></script>

    <!--custome script for all page-->
    <script src="{% static "UserPage/js/scripts.js" %}"></script>
    <!-- custom script for this page-->
    <script src="{% static "UserPage/js/sparkline-chart.js" %}"></script>
    <script src="{% static "UserPage/js/easy-pie-chart.js" %}"></script>
    <script src="{% static "UserPage/js/jquery-jvectormap-1.2.2.min.js" %}"></script>
    <script src="{% static "UserPage/js/jquery-jvectormap-world-mill-en.js" %}"></script>
    <script src="{% static "UserPage/js/xcharts.min.js" %}"></script>
    <script src="{% static "UserPage/js/jquery.autosize.min.js" %}"></script>
    <script src="{% static "UserPage/js/jquery.placeholder.min.js" %}"></script>
    <script src="{% static "UserPage/js/gdp-data.js" %}"></script>
    <script src="{% static "UserPage/js/morris.min.js" %}"></script>
    <script src="{% static "UserPage/js/sparklines.js" %}"></script>
    <script src="{% static "UserPage/js/charts.js" %}"></script>
    <script src="{% static "UserPage/js/jquery.slimscroll.min.js" %}"></script>
    <script>
      //knob
      $(function() {
        $(".knob").knob({
          'draw': function() {
            $(this.i).val(this.cv + '%')
          }
        })
      });

      //carousel
      $(document).ready(function() {
        $("#owl-slider").owlCarousel({
          navigation: true,
          slideSpeed: 300,
          paginationSpeed: 400,
          singleItem: true

        });
      });

      //custom select box

      $(function() {
        $('select.styled').customSelect();
      });

      /* ---------- Map ---------- */
      $(function() {
        $('#map').vectorMap({
          map: 'world_mill_en',
          series: {
            regions: [{
              values: gdpData,
              scale: ['#000', '#000'],
              normalizeFunction: 'polynomial'
            }]
          },
          backgroundColor: '#eef3f7',
          onLabelShow: function(e, el, code) {
            el.html(el.html() + ' (GDP - ' + gdpData[code] + ')');
          }
        });
      });
    </script>

</body>

</html>